# Generated by Django 3.1.2 on 2021-01-24 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productname',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aaa', to='shop_app.buyer'),
        ),
        migrations.AlterField(
            model_name='productname',
            name='product_price',
            field=models.IntegerField(default='', max_length=7, null=True),
        ),
    ]
