# Generated by Django 3.1.2 on 2021-02-12 00:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_productname_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='mult_picture',
            field=models.FileField(default=django.utils.timezone.now, upload_to='pictures'),
            preserve_default=False,
        ),
    ]
