# Generated by Django 3.1.2 on 2021-01-24 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_auto_20210124_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='buyed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyed', to='shop_app.productname'),
        ),
        migrations.AlterField(
            model_name='productname',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to='shop_app.buyer'),
        ),
    ]
