# Generated by Django 3.1.5 on 2021-01-11 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_auto_20210111_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=0, help_text='Product name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_spec',
            field=models.TextField(default=django.utils.timezone.now, help_text='Product specs', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_app.category'),
        ),
    ]
