# Generated by Django 3.1.2 on 2021-02-12 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_productname_mult_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productname',
            name='mult_picture',
        ),
    ]
