# Generated by Django 3.1.2 on 2021-01-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_auto_20210124_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productname',
            name='product_price',
            field=models.IntegerField(default='', null=True),
        ),
    ]
