# Generated by Django 3.1.2 on 2021-01-25 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_auto_20210125_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='buyed',
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyed_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyed_item', to='shop_app.productname'),
        ),
    ]
