# Generated by Django 3.1.5 on 2021-01-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_buyers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyers',
            new_name='Buyer',
        ),
    ]
