# Generated by Django 3.1.2 on 2021-02-12 00:46

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_auto_20210212_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productname',
            name='product_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[200, 110], upload_to='pictures'),
        ),
    ]
