# Generated by Django 3.1.2 on 2021-01-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_auto_20210125_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='note',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
