# Generated by Django 3.1.2 on 2021-02-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
