# Generated by Django 3.1.2 on 2021-01-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_auto_20210125_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='note',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productname',
            name='product_description',
            field=models.TextField(max_length=500),
        ),
    ]
