# Generated by Django 3.1.2 on 2021-02-12 20:05

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_delete_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='picture_1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[200, 110], upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='productname',
            name='picture_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[200, 110], upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='productname',
            name='picture_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[200, 110], upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='productname',
            name='picture_4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[200, 110], upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='productname',
            name='picture_5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[200, 110], upload_to='pictures'),
        ),
    ]
