# Generated by Django 3.1.2 on 2021-02-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_auto_20210212_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productname',
            old_name='picture_1',
            new_name='product_picture_2',
        ),
        migrations.RenameField(
            model_name='productname',
            old_name='picture_2',
            new_name='product_picture_3',
        ),
        migrations.RenameField(
            model_name='productname',
            old_name='picture_3',
            new_name='product_picture_4',
        ),
        migrations.RenameField(
            model_name='productname',
            old_name='picture_4',
            new_name='product_picture_5',
        ),
        migrations.RenameField(
            model_name='productname',
            old_name='picture_5',
            new_name='product_picture_6',
        ),
    ]
