# Generated by Django 3.1.2 on 2021-01-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_auto_20210112_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Product name', max_length=255),
        ),
    ]
