# Generated by Django 3.1.2 on 2021-02-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0011_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
