# Generated by Django 3.1.2 on 2021-02-01 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0012_auto_20210125_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'get_latest_by': '-date_buyed'},
        ),
    ]
