# Generated by Django 3.1.2 on 2021-02-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0013_auto_20210213_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productname',
            old_name='product_picture',
            new_name='product_picture_1',
        ),
    ]
