# Generated by Django 3.1.2 on 2021-01-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0013_auto_20210112_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
    ]
