# Generated by Django 3.1.2 on 2021-02-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0013_auto_20210201_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'ordering': ['-date_buyed']},
        ),
    ]
