# Generated by Django 3.1.2 on 2021-02-03 22:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0014_auto_20210201_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productname',
            name='product_picture',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[200, 110], upload_to='pictures'),
        ),
    ]
