# Generated by Django 3.1.2 on 2021-01-12 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0015_auto_20210112_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='productname',
            old_name='product_description',
            new_name='product_instance_description',
        ),
        migrations.RenameField(
            model_name='productname',
            old_name='product_name',
            new_name='product_instance_name',
        ),
        migrations.RenameField(
            model_name='productname',
            old_name='product_type',
            new_name='product_instance_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='shop_app.category'),
        ),
    ]
