# Generated by Django 3.1.2 on 2021-02-15 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0015_auto_20210213_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productname',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to='shop_app.buyer'),
        ),
    ]
