# Generated by Django 3.1.2 on 2021-02-03 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0016_auto_20210204_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-brand_name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-category_name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='productname',
            options={'ordering': ['-date_posted']},
        ),
    ]
