# Generated by Django 3.1.2 on 2021-01-13 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0016_auto_20210112_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productname',
            old_name='product_instance_type',
            new_name='product_instance_category',
        ),
    ]
