# Generated by Django 3.1.2 on 2021-01-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0018_auto_20210113_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(help_text='Product name', max_length=255)),
                ('brand_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='shop_app.category')),
            ],
        ),
        migrations.AlterField(
            model_name='productname',
            name='product_object_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_app.brand'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
