# Generated by Django 3.1.2 on 2021-01-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0019_auto_20210113_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productname',
            old_name='product_object_category',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='productname',
            old_name='product_object_description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='productname',
            old_name='product_object_name',
            new_name='product_name',
        ),
    ]
