# Generated by Django 3.1.2 on 2021-02-16 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0019_auto_20210216_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productname',
            name='buyer',
        ),
        migrations.AddField(
            model_name='productname',
            name='buyer_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_name', to='shop_app.buyer'),
        ),
    ]
