# Generated by Django 3.1.2 on 2021-02-16 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0020_auto_20210216_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyed_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyed_item', to='shop_app.productname'),
        ),
    ]
