# Generated by Django 3.1.2 on 2021-01-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0020_auto_20210113_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productname',
            old_name='product_category',
            new_name='product_brand',
        ),
    ]
