# Generated by Django 3.1.2 on 2021-02-16 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0021_auto_20210216_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productname',
            old_name='buyer_name',
            new_name='sold_to',
        ),
    ]
