# Generated by Django 3.1.2 on 2021-01-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0021_auto_20210113_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productname',
            name='product_description',
            field=models.TextField(max_length=2000),
        ),
    ]
