# Generated by Django 3.1.2 on 2021-01-16 19:19

import ckeditor_uploader.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0025_remove_productname_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='product_picture',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
