# Generated by Django 3.1.2 on 2021-02-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0026_auto_20210216_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productname',
            name='sold_to',
        ),
    ]
