# Generated by Django 3.1.2 on 2021-01-16 21:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0026_productname_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productname',
            name='product_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[320, 240], upload_to='pictures'),
        ),
    ]
