# Generated by Django 3.1.2 on 2021-02-17 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0027_remove_productname_sold_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='buyed_item',
        ),
    ]
