# Generated by Django 3.1.2 on 2021-02-17 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0028_remove_buyer_buyed_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='sold_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_to', to='shop_app.buyer'),
        ),
    ]
