# Generated by Django 3.1.2 on 2021-02-17 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0029_productname_sold_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='buyed_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyed_item', to='shop_app.productname'),
        ),
    ]
