# Generated by Django 3.1.2 on 2021-02-17 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0031_auto_20210217_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='name_confirm',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name_confirm', to='shop_app.productname'),
        ),
    ]
