# Generated by Django 3.1.2 on 2021-02-17 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0032_buyer_name_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='name_confirm',
        ),
    ]
